### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Cyprex** [Cyprex/tgs-minecraft#1]
- [ ] Add Ores to Advanced Rocketry Config as necessary
- [x] Add things to forestry backpacks
- [ ] Check if Pneumaticcraft oil lakes etc. need to be blacklisted from other dimensions.
- [x] Check if death location is broadcast or if only the player gets messaged their death location
- [ ] Add Ores to Minecolonies miner list
- [ ] Check Minecolonies commands
- [ ] Possibly add things to IEs toolboxes

**Comment by Cyprex** [comment]
Forestry already has good defaults nowadays. Hurray!
